/**
 * Setup - Environment Configuration
 *
 * A settings page for configuring the .env file
 * with individually saveable sections.
 *
 * Refactored from 1,717 lines to ~350 lines by extracting:
 * - Form components to components/setup/FormComponents.tsx
 * - Section definitions to components/setup/setupConstants.ts
 * - Individual sections to components/setup/sections/
 */

import { useState, useCallback, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useMutation, useQuery } from '@tanstack/react-query';
import { clsx } from 'clsx';
import toast from 'react-hot-toast';
import { Card } from '../components/Card';
import { api } from '../api/client';
import type { EnvironmentConfig } from '../types/setup';
import { defaultEnvironmentConfig } from '../types/setup';

// Import extracted components
import {
  LoadingSpinner,
  SECTIONS,
  LocationSyncPanel,
  EnvironmentSection,
  BackendDatabaseSection,
  XSightDatabaseSection,
  MobiControlDatabaseSection,
  LLMSection,
  MobiControlAPISection,
  StreamingSection,
  SecuritySection,
} from '../components/setup';

// Generate .env file content
function generateEnvContent(cfg: EnvironmentConfig): string {
  return `# =============================================================================
# SOTI Stella Sentinel - Environment Configuration
# =============================================================================
# Generated by Setup Wizard
# NEVER commit this .env file to version control.
# =============================================================================

# Application Environment
APP_ENV=${cfg.app_env}

# =============================================================================
# API Security & Tenant Context
# =============================================================================
REQUIRE_API_KEY=${cfg.require_api_key}
API_KEY=${cfg.api_key}
API_KEY_ROLE=${cfg.api_key_role}
TRUST_CLIENT_HEADERS=${cfg.trust_client_headers}
REQUIRE_TENANT_HEADER=${cfg.require_tenant_header}
DEFAULT_TENANT_ID=${cfg.default_tenant_id}
DEFAULT_USER_ROLE=${cfg.default_user_role}
TENANT_ID_ALLOWLIST=${cfg.tenant_id_allowlist}
ALLOW_IN_PROCESS_TRAINING=${cfg.allow_in_process_training}

# Observability
ENABLE_OTEL=${cfg.enable_otel}
OTEL_EXPORTER_OTLP_ENDPOINT=${cfg.otel_exporter_otlp_endpoint}
OTEL_EXPORTER_OTLP_INSECURE=${cfg.otel_exporter_otlp_insecure}
OTEL_SERVICE_NAME=${cfg.otel_service_name}
ENABLE_METRICS=${cfg.enable_metrics}
ENABLE_DB_METRICS=${cfg.enable_db_metrics}
ENABLE_TENANT_METRICS=${cfg.enable_tenant_metrics}
TENANT_METRICS_ALLOWLIST=${cfg.tenant_metrics_allowlist}
RESULTS_DB_USE_MIGRATIONS=${cfg.results_db_use_migrations}

# =============================================================================
# Frontend Configuration
# =============================================================================
FRONTEND_PORT=${cfg.frontend_port}
FRONTEND_DEV_PORT=${cfg.frontend_dev_port}
VITE_TENANT_ID=${cfg.vite_tenant_id}
VITE_API_KEY=${cfg.vite_api_key}
VITE_USER_ID=${cfg.vite_user_id}
VITE_USER_ROLE=${cfg.vite_user_role}

# =============================================================================
# PostgreSQL Backend Database
# =============================================================================
BACKEND_DB_HOST=${cfg.backend_db_host}
BACKEND_DB_PORT=${cfg.backend_db_port}
BACKEND_DB_NAME=${cfg.backend_db_name}
BACKEND_DB_USER=${cfg.backend_db_user}
BACKEND_DB_PASS=${cfg.backend_db_pass}
BACKEND_DB_CONNECT_TIMEOUT=${cfg.backend_db_connect_timeout}
BACKEND_DB_STATEMENT_TIMEOUT_MS=${cfg.backend_db_statement_timeout_ms}

# =============================================================================
# SOTI XSight SQL Server Configuration
# =============================================================================
DW_DB_HOST=${cfg.dw_db_host}
DW_DB_PORT=${cfg.dw_db_port}
DW_DB_NAME=${cfg.dw_db_name}
DW_DB_USER=${cfg.dw_db_user}
DW_DB_PASS=${cfg.dw_db_pass}
DW_DB_DRIVER=${cfg.dw_db_driver}
DW_DB_CONNECT_TIMEOUT=${cfg.dw_db_connect_timeout}
DW_DB_QUERY_TIMEOUT=${cfg.dw_db_query_timeout}
DW_TRUST_SERVER_CERT=${cfg.dw_trust_server_cert}

# =============================================================================
# SOTI MobiControl SQL Server Configuration (Optional)
# =============================================================================
MC_DB_HOST=${cfg.mc_db_host}
MC_DB_PORT=${cfg.mc_db_port}
MC_DB_NAME=${cfg.mc_db_name}
MC_DB_USER=${cfg.mc_db_user}
MC_DB_PASS=${cfg.mc_db_pass}
MC_DB_DRIVER=${cfg.mc_db_driver}
MC_DB_CONNECT_TIMEOUT=${cfg.mc_db_connect_timeout}
MC_DB_QUERY_TIMEOUT=${cfg.mc_db_query_timeout}
MC_TRUST_SERVER_CERT=${cfg.mc_trust_server_cert}

# =============================================================================
# LLM Configuration
# =============================================================================
ENABLE_LLM=${cfg.enable_llm}
LLM_BASE_URL=${cfg.llm_base_url}
LLM_API_KEY=${cfg.llm_api_key}
LLM_MODEL_NAME=${cfg.llm_model_name}
LLM_API_VERSION=${cfg.llm_api_version}
LLM_BASE_URL_ALLOWLIST=${cfg.llm_base_url_allowlist}

# =============================================================================
# Real-Time Streaming Configuration
# =============================================================================
ENABLE_STREAMING=${cfg.enable_streaming}
REDIS_URL=${cfg.redis_url}
REDIS_DB=${cfg.redis_db}
STREAM_BUFFER_SIZE=${cfg.stream_buffer_size}
STREAM_FLUSH_INTERVAL_MS=${cfg.stream_flush_interval_ms}

# =============================================================================
# SOTI MobiControl API Configuration (Optional)
# =============================================================================
MOBICONTROL_SERVER_URL=${cfg.mobicontrol_server_url}
MOBICONTROL_CLIENT_ID=${cfg.mobicontrol_client_id}
MOBICONTROL_CLIENT_SECRET=${cfg.mobicontrol_client_secret}
MOBICONTROL_USERNAME=${cfg.mobicontrol_username}
MOBICONTROL_PASSWORD=${cfg.mobicontrol_password}
MOBICONTROL_TENANT_ID=${cfg.mobicontrol_tenant_id}
`;
}

export default function Setup() {
  const [activeSection, setActiveSection] = useState('environment');
  const [config, setConfig] = useState<EnvironmentConfig>(defaultEnvironmentConfig);
  const [showPasswords, setShowPasswords] = useState<Record<string, boolean>>({});
  const [savingSection, setSavingSection] = useState<string | null>(null);
  const [configLoaded, setConfigLoaded] = useState(false);

  // Fetch current configuration from backend
  const { data: savedConfig, isLoading: isLoadingConfig } = useQuery({
    queryKey: ['setup-config'],
    queryFn: () => api.getSetupConfig(),
    staleTime: 0,
    refetchOnWindowFocus: false,
  });

  // Merge saved config with defaults when data is loaded
  useEffect(() => {
    if (savedConfig && !configLoaded) {
      const mergedConfig = {
        ...defaultEnvironmentConfig,
        ...savedConfig,
      } as EnvironmentConfig;
      setConfig(mergedConfig);
      setConfigLoaded(true);
    }
  }, [savedConfig, configLoaded]);

  // Update config helper
  const updateConfig = useCallback(<K extends keyof EnvironmentConfig>(
    key: K,
    value: EnvironmentConfig[K]
  ) => {
    setConfig((prev) => ({ ...prev, [key]: value }));
  }, []);

  // Toggle password visibility
  const togglePassword = (field: string) => {
    setShowPasswords((prev) => ({ ...prev, [field]: !prev[field] }));
  };

  // Save section mutation
  const saveSectionMutation = useMutation({
    mutationFn: (section: string) => api.saveSetupConfig({ section, config: config as unknown as Record<string, unknown> }),
    onMutate: (section) => setSavingSection(section),
    onSuccess: (data) => {
      if (data.success) {
        toast.success('Settings saved successfully!');
      } else {
        toast.error(data.message);
      }
      setSavingSection(null);
    },
    onError: (error: Error) => {
      toast.error(`Failed to save: ${error.message}`);
      setSavingSection(null);
    },
  });

  // Save full configuration mutation
  const saveMutation = useMutation({
    mutationFn: () => api.saveSetupConfig(config as unknown as Record<string, unknown>),
    onSuccess: (data) => {
      if (data.success) {
        toast.success('Configuration saved successfully!');
      } else {
        toast.error(data.message);
      }
    },
    onError: (error: Error) => {
      toast.error(`Failed to save: ${error.message}`);
    },
  });

  // Save a specific section
  const saveSection = (sectionId: string) => {
    saveSectionMutation.mutate(sectionId);
  };

  // Download as .env file
  const downloadEnvFile = () => {
    const envContent = generateEnvContent(config);
    const blob = new Blob([envContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = '.env';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success('.env file downloaded!');
  };

  // Common props for section components
  const sectionProps = {
    config,
    updateConfig,
    showPasswords,
    togglePassword,
    savingSection,
  };

  // Render section content
  const renderSectionContent = () => {
    switch (activeSection) {
      case 'environment':
        return <EnvironmentSection {...sectionProps} onSave={() => saveSection('environment')} />;
      case 'backend-db':
        return <BackendDatabaseSection {...sectionProps} onSave={() => saveSection('backend-db')} />;
      case 'xsight-db':
        return <XSightDatabaseSection {...sectionProps} onSave={() => saveSection('xsight-db')} />;
      case 'mobicontrol-db':
        return <MobiControlDatabaseSection {...sectionProps} onSave={() => saveSection('mobicontrol-db')} />;
      case 'llm':
        return <LLMSection {...sectionProps} onSave={() => saveSection('llm')} />;
      case 'mobicontrol-api':
        return <MobiControlAPISection {...sectionProps} onSave={() => saveSection('mobicontrol-api')} />;
      case 'streaming':
        return <StreamingSection config={config} updateConfig={updateConfig} savingSection={savingSection} onSave={() => saveSection('streaming')} />;
      case 'location-sync':
        return <LocationSyncPanel />;
      case 'security':
        return <SecuritySection {...sectionProps} onSave={() => saveSection('security')} />;
      default:
        return null;
    }
  };

  const currentSection = SECTIONS.find(s => s.id === activeSection) || SECTIONS[0];

  // Show loading state while fetching config
  if (isLoadingConfig) {
    return (
      <motion.div
        className="flex items-center justify-center min-h-[400px]"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
      >
        <div className="text-center">
          <LoadingSpinner />
          <p className="text-slate-400 mt-4">Loading current configuration...</p>
        </div>
      </motion.div>
    );
  }

  return (
    <motion.div
      className="space-y-6"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
    >
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold text-white">Settings</h1>
          <p className="text-slate-500 mt-1">Configure your environment settings individually</p>
        </div>
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={downloadEnvFile}
            className="flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium bg-slate-700/50 text-slate-300 hover:bg-slate-700 border border-slate-600/50 transition-all"
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            Export .env
          </button>
          <button
            type="button"
            onClick={() => saveMutation.mutate()}
            disabled={saveMutation.isPending}
            className="flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium btn-stellar"
          >
            {saveMutation.isPending ? (
              <>
                <LoadingSpinner />
                Saving...
              </>
            ) : (
              <>
                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-3m-1 4l-3 3m0 0l-3-3m3 3V4" />
                </svg>
                Save All
              </>
            )}
          </button>
        </div>
      </div>

      {/* Main Content - Two Column Layout */}
      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
        {/* Section Navigation Sidebar */}
        <div className="lg:col-span-1">
          <Card noPadding>
            <nav className="p-2 space-y-1">
              {SECTIONS.map((section) => (
                <button
                  key={section.id}
                  type="button"
                  onClick={() => setActiveSection(section.id)}
                  className={clsx(
                    'w-full flex items-center gap-3 px-3 py-2.5 rounded-lg transition-all text-left',
                    activeSection === section.id
                      ? 'bg-amber-500/20 text-amber-400 border border-amber-500/30'
                      : 'text-slate-400 hover:bg-slate-800/50 hover:text-slate-300 border border-transparent'
                  )}
                >
                  <div
                    className={clsx(
                      'w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0',
                      activeSection === section.id
                        ? 'bg-amber-500/30 text-amber-400'
                        : 'bg-slate-800 text-slate-500'
                    )}
                  >
                    {section.icon}
                  </div>
                  <div className="min-w-0">
                    <p className="text-sm font-medium truncate">{section.title}</p>
                    <p className="text-xs text-slate-500 truncate">{section.description}</p>
                  </div>
                </button>
              ))}
            </nav>
          </Card>
        </div>

        {/* Section Content */}
        <div className="lg:col-span-3">
          <Card>
            <div className="mb-6">
              <div className="flex items-center gap-3 mb-2">
                <div className="w-10 h-10 rounded-lg bg-amber-500/20 flex items-center justify-center text-amber-400">
                  {currentSection.icon}
                </div>
                <div>
                  <h2 className="text-xl font-bold text-white">{currentSection.title}</h2>
                  <p className="text-sm text-slate-500">{currentSection.description}</p>
                </div>
              </div>
            </div>

            <AnimatePresence mode="wait">
              <motion.div
                key={activeSection}
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                transition={{ duration: 0.2 }}
              >
                {renderSectionContent()}
              </motion.div>
            </AnimatePresence>
          </Card>
        </div>
      </div>
    </motion.div>
  );
}
